# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy GH Page and NPM Package

on:
  push:
    branches: [ main, release_1.0 ]

jobs:
#  github_pages:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout 🛎️
#        uses: actions/checkout@v2

#      - name: Use Node.js (18)
#        uses: actions/setup-node@v1
#        with:
#          node-version: '18'

#      - name: Install and Build 🔧
#        run: |
#          npm ci
#          npm run build:demo

#      - name: Deploy 🚀
#        uses: JamesIves/github-pages-deploy-action@4.1.3
#        with:
#          BRANCH: gh-pages
#          FOLDER: demo/dist

  semantic_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Use Node.js (18)
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install dependencies 🔧
        run: npm ci

      - name: Release 🚀
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
